export const config = {
    tree: { width: window.innerWidth < 600 ? window.innerWidth - 40 : 800, height: 600 },
    particles: { number: window.innerWidth < 600 ? 20 : 50 },
    api: 'http://localhost:8080/api',
    webappUrl: 'https://example.com', // Placeholder: Update with your actual deployed WebApp URL
    lang: navigator.language.startsWith('ru') ? 'ru' : 'en',
    translations: {
        ru: {
            welcome: 'Привет, {name}!',
            title: 'Децентрализованная сеть Пирамиды Богатства 🤑',
            event: '🔥 Лимитированный ивент!',
            timer: 'Осталось: {time}',
            join: 'Вступить 🤑',
            buyPower: 'Купить мощность ⚡',
            withdraw: 'Вывод 💸',
            joinGuild: 'Вступить в гильдию 🛡️',
            vote: 'Голосовать 📊',
            leaderboard: 'Лидерборд 🥇',
            payUSD: 'Оплатить в USD 💵',
            quests: '🎯 Квесты',
            achievements: '🏆 Достижения',
            guild: '🛡️ Гильдия',
            guildNone: 'Ты пока не в гильдии',
            tree: 'Дерево децентрализованной сети 🌳',
            fan: 'Вентилятор пассивного дохода: {speed}x',
            voting: 'Голосование за процент выплат',
            votingTimer: 'Голосование заканчивается: {time}',
            noVoting: 'Не активно',
            modalJoin: 'Вступление в пирамиду',
            modalPower: 'Покупка мощности',
            modalGuild: 'Вступление в гильдии',
            modalVote: 'Голосование за процент',
            modalPay: 'Оплата в USD',
            inputAmount: 'Сумма в USD',
            inputPower: 'Количество мощности',
            inputGuild: 'ID гильдии (1 и выше)',
            inputVote: 'Процент выплат (10-50)',
            errorWallet: 'Установи MetaMask!',
            errorConnect: 'Ошибка подключения кошелька!',
            errorJoin: 'Ошибка вступления!',
            errorPower: 'Ошибка покупки мощности!',
            errorWithdraw: 'Ошибка вывода!',
            errorGuild: 'Ошибка вступления в гильдию!',
            errorVote: 'Ошибка голосования!',
            errorPayment: 'Ошибка оплаты!',
            errorApi: 'Ошибка API!',
            successJoin: 'Ты в игре, пиздец!',
            successPower: 'Мощность куплена!',
            successWithdraw: 'Средства выведены!',
            successGuild: 'Ты в гильдии, братан!',
            successVote: 'Голос учтён!',
            successPayment: 'Оплата прошла, токены начислены!',
            invalidAmount: 'Недопустимая сумма!',
            invalidPower: 'Недопустимое количество!',
            invalidGuild: 'Недопустимый ID гильдии!',
            invalidVote: 'Процент должен быть 10-50!',
            insufficientBalance: 'Недостаточно USD!',
            transactionLimit: 'Слишком много транзакций! Подожди час.',
            captchaRequired: 'Пройди проверку: https://captcha.pyramid.io'
        },
        en: {
            welcome: 'Hello, {name}!',
            title: 'Decentralized Wealth Pyramid Network 🤑',
            event: '🔥 Limited Event!',
            timer: 'Time left: {time}',
            join: 'Join 🤑',
            buyPower: 'Buy Power ⚡',
            withdraw: 'Withdraw 💸',
            joinGuild: 'Join Guild 🛡️',
            vote: 'Vote 📊',
            leaderboard: 'Leaderboard 🥇',
            payUSD: 'Pay in USD 💵',
            quests: '🎯 Quests',
            achievements: '🏆 Achievements',
            guild: '🛡️ Guild',
            guildNone: 'You are not in a guild yet',
            tree: 'Decentralized Network Tree 🌳',
            fan: 'Passive Income Fan: {speed}x',
            voting: 'Payout Percentage Voting',
            votingTimer: 'Voting ends: {time}',
            noVoting: 'Not active',
            modalJoin: 'Join Pyramid',
            modalPower: 'Buy Power',
            modalGuild: 'Join Guild',
            modalVote: 'Vote for Payout Percent',
            modalPay: 'Pay in USD',
            inputAmount: 'Amount in USD',
            inputPower: 'Power amount',
            inputGuild: 'Guild ID (1 or higher)',
            inputVote: 'Payout percent (10-50)',
            errorWallet: 'Install MetaMask!',
            errorConnect: 'Wallet connection error!',
            errorJoin: 'Join error!',
            errorPower: 'Power purchase error!',
            errorWithdraw: 'Withdraw error!',
            errorGuild: 'Guild join error!',
            errorVote: 'Voting error!',
            errorPayment: 'Payment error!',
            errorApi: 'API error!',
            successJoin: 'You’re in, hell yeah!',
            successPower: 'Power purchased!',
            successWithdraw: 'Funds withdrawn!',
            successGuild: 'Joined guild, bro!',
            successVote: 'Vote counted!',
            successPayment: 'Payment successful, tokens minted!',
            invalidAmount: 'Invalid amount!',
            invalidPower: 'Invalid amount!',
            invalidGuild: 'Invalid guild ID!',
            invalidVote: 'Percent must be 10-50!',
            insufficientBalance: 'Insufficient USD!',
            transactionLimit: 'Too many transactions! Wait an hour.',
            captchaRequired: 'Complete verification: https://captcha.pyramid.io'
        }
    }
};

export function t(key, params = {}) {
    let str = config.translations[config.lang][key] || key;
    for (const [k, v] of Object.entries(params)) {
        str = str.replace(`{${k}}`, DOMPurify.sanitize(v));
    }
    return str;
}